openapi: 3.0.0
info:
  title: Storyteller
  description: This is the API documentation for the server based on the OpenAPI 3.0 specification.
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: 'OK'
  /get-users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
  /login:
    post:
      summary: Login endpoint
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Logged in successfully'
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Invalid username or password'
  /register:
    post:
      summary: Register a new user
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'User registered successfully'
                  userId:
                    type: integer
                    example: 1
        '400':
          description: Username already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Username already exists'
